/*! \file kogmo_rtdb_obj_tids.h
 * \brief List of Objects-Type-IDs
 *
 * Copyright (c) 2007 Matthias Goebl <matthias.goebl*goebl.net>
 *     Lehrstuhl fuer Realzeit-Computersysteme (RCS)
 *     Technische Universitaet Muenchen (TUM)
 *   and Project Partners of SFB/TR 28 "Kognitive Automobile"
 */

#ifndef KOGMO_RTDB_OBJ_TIDS_H
#define KOGMO_RTDB_OBJ_TIDS_H



enum kogmo_rtdb_objtype {
 #define KOGMO_RTDB_WITHIN_OBJ_TYPEIDS_ENUM

 #include "kogmo_rtdb_obj_base.id"

 #ifdef    KOGMO_RTDB_OBJ_TYPEIDS_AUTOGENERATED_FILE
  #include KOGMO_RTDB_OBJ_TYPEIDS_AUTOGENERATED_FILE
 #endif

 /*
   Object Type-ID allocated ranges:
   ================================
   Reg.Pattern  User        Current Use
   0x0000xxxx   Reserved
   0x00Axxxxx   SFB/TR 28   A[01234AF]
   0x00Bxxxxx   SFB/TR 28   B[12]
   0x00Cxxxxx   SFB/TR 28   C[1234]
   0x00Dxxxxx   SFB/TR 28   D1
   0x00Exxxxx   SFB/TR 28
   0x00Fxxxxx   SFB/TR 28   FB
   0x0CYYXXXX   CoteSys     YY=Teilprojekt, z.B. 0x0CA10010

   For a global registration of your id-space, please mail to mattias.goebl*kogmo-rtdb.de

 */

 #ifdef    KOGMO_RTDB_OBJ_TYPEIDS_PROJECT1_FILE
  #include KOGMO_RTDB_OBJ_TYPEIDS_PROJECT1_FILE
 #endif

 #ifdef    KOGMO_RTDB_OBJ_TYPEIDS_SUBPROJECT1_FILE
  #include KOGMO_RTDB_OBJ_TYPEIDS_SUBPROJECT1_FILE
 #endif

 #ifdef    KOGMO_RTDB_OBJ_TYPEIDS_PRIVATE1_FILE
  #include KOGMO_RTDB_OBJ_TYPEIDS_PRIVATE1_FILE
 #endif

 #ifdef    KOGMO_RTDB_OBJ_TYPEIDS_PROJECT2_FILE
  #include KOGMO_RTDB_OBJ_TYPEIDS_PROJECT2_FILE
 #endif

 #ifdef    KOGMO_RTDB_OBJ_TYPEIDS_SUBPROJECT2_FILE
  #include KOGMO_RTDB_OBJ_TYPEIDS_SUBPROJECT2_FILE
 #endif

 #ifdef    KOGMO_RTDB_OBJ_TYPEIDS_PRIVATE2_FILE
  #include KOGMO_RTDB_OBJ_TYPEIDS_PRIVATE2_FILE
 #endif


 #undef KOGMO_RTDB_WITHIN_OBJ_TYPEIDS_ENUM
};

// KogniMobil-Compatibility:
#define KOGMO_RTDB_OBJ_TYPEIDS_H

#endif /* KOGMO_RTDB_OBJ_TIDS_H */
