/*! \file kogmo_rtdb.h
 * \brief Master-Header to access the Real-time Vehicle Database
 *
 * Copyright (c) 2003-2006 Matthias Goebl <matthias.goebl*goebl.net>
 *     Lehrstuhl fuer Realzeit-Computersysteme (RCS)
 *     Technische Universitaet Muenchen (TUM)
 */

#ifndef KOGMO_RTDB_H
#define KOGMO_RTDB_H


// This is for backwards compatibility of our existing KogniMobil-Project Code
// This will be removed in the future.. (mg)
#ifdef KOGNIMOBIL_OLD_INCLUDES
 #ifndef  KOGMO_RTDB_OBJ_TYPEIDS_PROJECT1_FILE
  #define KOGMO_RTDB_OBJ_TYPEIDS_PROJECT1_FILE "kogmo_rtdb_obj_typeids.h"
 #endif
 #ifndef  KOGMO_RTDB_OBJ_DEFS_PROJECT1_FILE
  #define KOGMO_RTDB_OBJ_DEFS_PROJECT1_FILE "kogmo_rtdb_obj_defs.h"
 #endif
 #ifndef  KOGMO_RTDB_OBJ_CLASSES_PROJECT1_FILE
  #define KOGMO_RTDB_OBJ_CLASSES_PROJECT1_FILE "kogmo_rtdb_obj_classes.hxx"
 #endif
#endif


// Define RTDB-Types and Functions
#include "kogmo_time.h"
#include "kogmo_rtdb_types.h"
#include "kogmo_rtdb_funcs.h"

// Define Object Type-IDs
#include "kogmo_rtdb_obj_tids.h"

// Define Basic Objects
#include "kogmo_rtdb_obj_base.h"
#include "kogmo_rtdb_obj_base_funcs.h"

// Define C++ - Access Methods and Object Wrappers
#ifdef __cplusplus
 #include "kogmo_time.hxx"
 #include "kogmo_rtdb_conn.hxx"
 #include "kogmo_rtdb_obj_base_classes.hxx"
 #include "kogmo_rtdb_obj_base_system_classes.hxx"
#endif


// Macro for Quick'n'Dirty Object Definitions
#ifdef __cplusplus
 #define DEFINE_KOGMO_RTDB_OBJECT(Name,TypeID,Description,Definition) \
 namespace KogniMobil { \
  extern "C" { \
   /*! \brief Description */ \
   typedef PACKED_struct { \
     Definition \
   } kogmo_rtdb_subobj_ ## Name ## _t; \
   typedef PACKED_struct { \
     kogmo_rtdb_subobj_base_t base; \
     kogmo_rtdb_subobj_ ## Name ## _t data; \
   } kogmo_rtdb_obj_ ## Name ## _t; \
  }; \
  typedef RTDBObj_T < kogmo_rtdb_subobj_ ## Name ## _t, TypeID /* _KOGMO_RTDB_OBJTYPE_ ## Name */, RTDBObj > Name ## _T; \
 }
#else /* no C++ */
 #define DEFINE_KOGMO_RTDB_OBJECT(Name,TypeID,Description,Definition) \
   /*! \brief Description */ \
   typedef PACKED_struct { \
     Definition \
   } kogmo_rtdb_subobj_ ## Name ## _t; \
   typedef PACKED_struct { \
     kogmo_rtdb_subobj_base_t base; \
     kogmo_rtdb_subobj_ ## Name ## _t data; \
   } kogmo_rtdb_obj_ ## Name ## _t;
#endif




// Define User Objects

#if ! defined(KOGMO_RTDB_DONT_INCLUDE_ALL_OBJECTS)

 #ifdef    KOGMO_RTDB_OBJ_DEFS_PROJECT1_FILE
  #include KOGMO_RTDB_OBJ_DEFS_PROJECT1_FILE
 #endif

 #ifdef    KOGMO_RTDB_OBJ_DEFS_SUBPROJECT1_FILE
  #include KOGMO_RTDB_OBJ_DEFS_SUBPROJECT1_FILE
 #endif

 #ifdef    KOGMO_RTDB_OBJ_DEFS_PRIVATE1_FILE
  #include KOGMO_RTDB_OBJ_DEFS_PRIVATE1_FILE
 #endif

 #ifdef    KOGMO_RTDB_OBJ_DEFS_PROJECT2_FILE
  #include KOGMO_RTDB_OBJ_DEFS_PROJECT2_FILE
 #endif

 #ifdef    KOGMO_RTDB_OBJ_DEFS_SUBPROJECT2_FILE
  #include KOGMO_RTDB_OBJ_DEFS_SUBPROJECT2_FILE
 #endif

 #ifdef    KOGMO_RTDB_OBJ_DEFS_PRIVATE2_FILE
  #include KOGMO_RTDB_OBJ_DEFS_PRIVATE2_FILE
 #endif

 #ifdef    KOGMO_RTDB_OBJ_DEFS_AUTOGENERATED_FILE
  #include KOGMO_RTDB_OBJ_DEFS_AUTOGENERATED_FILE
 #endif


 #ifdef __cplusplus

 #ifdef    KOGMO_RTDB_OBJ_CLASSES_PROJECT1_FILE
  #include KOGMO_RTDB_OBJ_CLASSES_PROJECT1_FILE
 #endif

 #ifdef    KOGMO_RTDB_OBJ_CLASSES_SUBPROJECT1_FILE
  #include KOGMO_RTDB_OBJ_CLASSES_SUBPROJECT1_FILE
 #endif

 #ifdef    KOGMO_RTDB_OBJ_CLASSES_PRIVATE1_FILE
  #include KOGMO_RTDB_OBJ_CLASSES_PRIVATE1_FILE
 #endif

 #ifdef    KOGMO_RTDB_OBJ_CLASSES_PROJECT2_FILE
  #include KOGMO_RTDB_OBJ_CLASSES_PROJECT2_FILE
 #endif

 #ifdef    KOGMO_RTDB_OBJ_CLASSES_SUBPROJECT2_FILE
  #include KOGMO_RTDB_OBJ_CLASSES_SUBPROJECT2_FILE
 #endif

 #ifdef    KOGMO_RTDB_OBJ_CLASSES_PRIVATE2_FILE
  #include KOGMO_RTDB_OBJ_CLASSES_PRIVATE2_FILE
 #endif

 #include "kogmo_rtdb_obj_dump.hxx"

 #endif /* __cplusplus */

#endif /* ! defined(KOGMO_RTDB_DONT_INCLUDE_ALL_OBJECTS) */


#endif /* KOGMO_RTDB_OBJS_H */
